export const ADD_USER = 'ADD_USER';

export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_QUESTIONS = 'ADD_QUESTIONS'
export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';
export const QUESTIONS_FAILED = 'QUESTIONS_FAILED';

export const ADD_SCENARIO = 'ADD_SCENARIO';
export const ADD_SCENARIOS = 'ADD_SCENARIOS'
export const SCENARIOS_LOADING = 'SCENARIOS_LOADING';
export const SCENARIOS_FAILED = 'SCENARIOS_FAILED';

export const ADD_INFO = 'ADD_INFO';
export const ADD_INFORMATION = 'ADD_INFORMATION';
export const INFO_LOADING = 'INFO_LOADING';
export const INFO_FAILED = 'INFO_FAILED';